### ISSUE TITLE
Login through CAS doesn't work on mobile

### ISSUE THREAD

**Issue by IAmWave** [ReCodEx/web-app#154]
When I try to log in through CAS on my phone, I get taken back to the main page, but when I expand the sidebar again, there is just the "sign in" button - it doesn't actually sign me in.

Android 8.1.0, Firefox 57.

**Comment by SemaiCZE** [comment]
Hi,
Chrome browser works fine. FF has been completely broken untill recently (due to issues with intl support). We will try to investigate further, but with a low priority. Any contributions ale welcome :).

**Comment by Sejsel** [comment]
I have similar issues with Firefox 57 on desktop, it usually takes two tries to actually log in. I don't have this issue with other webpages that use CAS login, for example the [Data Structures course submission webpage](https://kam.mff.cuni.cz/~ds1/) works perfectly. It might be connected to the fact that the app opens the CAS window in another tab (why?).

**Comment by Neloop** [comment]
Hello,
yes, this is a known problem and currently we have no idea why this is happening on desktop Firefox. As @SemaiCZE said Chrome, even on desktop, works fine. We are going to look at this as soon as possible, I agree that it is quite annoying.

**Comment by Sejsel** [comment]
I checked my Firefox install and it also had the restriction set to `0` instead of `2`. In any case, that only changes how the new window is displayed. I am curious whether there is any reason to open another window.

I prefer to go "through" the CAS login form instead of having multiple tabs/windows open. I believe that might also be the reason why it fails on mobile (and sometimes desktop) Firefox. Is there any reason to open a new window with the CAS login form instead of redirecting to CAS and then getting redirected back?

**Comment by Neloop** [comment]
Oh, ok... sorry, I thought your problem was with opening in tab, not in separate window. In that case... It is quite common to open this login forms in new popup windows (At least with services implementing OAuth login system). That is why this approach was implemented. Of course if there are problems with it, we can reimplement this using redirections... and we probably will.

**Comment by krulis-martin** [comment]
New version was released on primary MFF server. Try it now.

**Comment by Sejsel** [comment]
I just tried to sign in in mobile Firefox 57 and instead of being logged in I got a notification 
> Server response: The ticket 'ST-13...-........-idp.cuni.cz' is not valid and does not belong to a CUNI student or staff or it was already used.

**Comment by krulis-martin** [comment]
Did you load a fresh version of the app?

**Comment by Sejsel** [comment]
Yes, it had the new loading screen. I tried it one more time and this time it worked even on mobile Firefox.

**Comment by krulis-martin** [comment]
I am sorry, it works fine on my Android FF (just tested). Cannot replicate the problem.

**Comment by Sejsel** [comment]
I will let you know if it happens again, it might have been something cached.
