### ISSUE TITLE
Lack of evaluation log

### ISSUE THREAD

**Issue by astodetokerencineltumomelrimo** [ReCodEx/web-app#200]
Hi,
evaluation process in CodEx used to display evaluation logs:
>Test 1... <init> <run> SG:Caught fatal signal 11 (SIGSEGV)

while ReCoDex displays:
![image](https://user-images.githubusercontent.com/27077791/37296663-ede24e60-261b-11e8-8c27-12806db7dccd.png)
wich I don't find very useful.

Are you planning to add such feature? Thanks

**Comment by SemaiCZE** [comment]
Hi,

managed languages like Java or C# are executed through a wrapper translating some exceptions to error codes for which we provide a mapping to text messages. For C++ it is much harder, because anything could be an exception. Until recently there was an issue with correct handling of signals in the Isolate sandbox, so maybe now we could show a killing signal, but I'm not sure about this and definitely it is not our priority. Pull requests are welcomed.

Your issue does not specify which language are you using, but i suppose it is C++. However, main goal of ReCodEx is not be a friendly debugging tool, so there is no much information comming directly from your program presented in the UI because it could lead to leaking of testing data. It is part of your task to make your program correct before you try to submit it to ReCodEx. From your results I suppose that test 2 is unhadled exception and tests 3 and 5 just give wrong answer.

**Comment by krulis-martin** [comment]
I would add one short comment. Actually, we do not plan to add this kind of feature in the future (at least not generally available) as it is potential security leak. There is some support to debug submitted solutions by teachers, so you may ask your teacher for help...
