### ISSUE TITLE
Feature request: diff tool for submitted solutions

### ISSUE THREAD

**Issue by t-macho** [ReCodEx/web-app#450]
As a student who often submits many different solutions with small changes (e.g. one bugfix at a time), I'd really appreciate some kind of diff tool that would enable comparing two (or multiple) submitted solutions.
It's rather clumsy now in a sense that I have to open multiple tabs (solutions), view source code for each solution (and each file if there are more, which can't be done at once) and then copy it to some diff tool.

**Comment by Teyras** [comment]
I suggest that you use `git` for this purpose. Its authors have done a good enough job and it's unlikely we can do better anytime soon.

**Comment by t-macho** [comment]
I understand that, but having many "small" homeworks, managing repo for each subject seems impractical, often it would mean spending more time fiddling with git than on the actual homeworks.

**Comment by Teyras** [comment]
I met a bunch of people who did exactly that, but it's not necessary to make a new Github repository for each assignment - a simple `git init` and then `git commit` for each meaningful change can give you the functionality you request. Also, if you use VS code, the git integration there is quite pleasant to use (and it's a valuable skill to have).

**Comment by krulis-martin** [comment]
This feature request has already been registered. However, the problem is slightly more complicated since ReCodEx does not keep diffs natively like git and subsequent submissions are treated as completely independent and there are also solutions that have many files.
Bottom line is that such a feature will not be implemented any time soon since it requires some more discussion and we have quite a list of things with higher priority. As an immediate out of the box solution, I would suggest to use `git` as @Teyras did. You can create local git repo and use ReCodEx CLI (with your own scripts) to fill it. If you are MFF teacher, ask Jiri Fink who is probably doing something like this already.
